name: Mosquitto & Tailscale
version: 0.2.8
slug: mosquitto-tailscale
description: Open source MQTT broker combined with zero config VPN
url: https://github.com/elcajon-tech/addon-mosquitto-tailscale
codenotary: codenotary@elcajon.dev
startup: system
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
init: false
hassio_api: true
map:
- config:rw
- share:rw
discovery:
- mqtt
services:
- mqtt:provide
privileged:
- NET_ADMIN
devices:
- /dev/net/tun
options:
  tailscale_authkey: ''
  logins: []
  customize:
    active: false
    folder: /share/mosquitto
schema:
  enable_tailscale_ssh: bool?
  tailscale_authkey: str?
  logins:
  - username: str
    password: password
  customize:
    active: bool
    folder: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.io/elcajon-tech/mosquitto-tailscale/{arch}
