arch:
- aarch64
- amd64
- armhf
- armv7
- i386
auth_api: true
codenotary: agonist02_stiel@icloud.com
description: Zero config VPN and network wide ad-blocking
devices:
- /dev/net/tun
discovery:
- adguard
hassio_api: true
hassio_role: manager
host_network: true
image: ghcr.io/elcajon-tech/adguard-tailscale/{arch}
ingress: true
ingress_port: 0
ingress_stream: true
init: false
name: Adguard & Tailscale
panel_icon: mdi:shield-check
ports:
  53/udp: 53
ports_description:
  53/udp: DNS server port
privileged:
- NET_ADMIN
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  tags:
  - match(^tag:[a-zA-Z0-9]+-?[a-zA-Z0-9]+$)?
slug: adguard-tailscale
startup: services
url: https://github.com/elcajon-tech/addon-adguard-tailscale
version: 0.2.0
