---
channel: stable
addons:
  vscode:
    repository: elcajon/addon-vscode
    target: vscode
    image: ghcr.io/elcajon/vscode/{arch}
  nextcloud:
    repository: elcajon/addon-nextcloud
    target: nextcloud
    image: ghcr.io/elcajon/nextcloud/{arch}
  duplicati:
    repository: elcajon/addon-duplicati
    target: duplicati
    image: ghcr.io/elcajon/duplicati/{arch}
