---
channel: stable
addons:
  code-server:
    repository: elcajon-tech/addon-code-server
    target: code-server
    image: ghcr.io/elcajon-tech/code-server/{arch}
  tailscale:
    repository: elcajon-tech/addon-tailscale
    target: tailscale
    image: ghcr.io/elcajon-tech/tailscale/{arch}
