---
channel: stable
addons:
  code-server:
    repository: elcajon-tech/addon-code-server
    target: code-server
    image: ghcr.io/elcajon-tech/code-server/{arch}
  adguard-tailscale:
    repository: elcajon-tech/addon-adguard-tailscale
    target: adguard-tailscale
    image: ghcr.io/elcajon-tech/adguard-tailscale/{arch}
  nextdns:
    repository: elcajon-tech/addon-nextdns
    target: nextdns
    image: ghcr.io/elcajon-tech/nextdns/{arch}
