---
  channel: stable
  addons:
    vscode:
      repository: elcajon/addon-vscode
      target: vscode
      image: ghcr.io/elcajon/vscode/{arch}
    generic:
      repository: elcajon/addon-generic
      target: generic
      image: ghcr.io/elcajon/generic/{arch}
