---
channel: stable
addons:
  vscode:
    repository: elcajon/addon-vscode
    target: vscode
    image: ghcr.io/elcajon/vscode/{arch}
  tor:
    repository: elcajon/addon-tor
    target: tor
    image: ghcr.io/elcajon/tor/{arch}
