arch:
- amd64
description: Simplelogin self-hosted Server
image: ghcr.io/elcajon/simplelogin/{arch}
ingress: true
init: false
map:
- ssl:rw
- share:rw
name: Simplelogin
options:
  certfile: fullchain.pem
  disable_registration: false
  keyfile: privkey.pem
  maildomain: null
  ssl: false
  webdomain: null
ports:
  25/tcp: 25
  80/tcp: 80
ports_description:
  25/tcp: SMTP
  80/tcp: Web interface
schema:
  certfile: str
  disable_registration: bool
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  maildomain: str
  ssl: bool
  webdomain: str
slug: simplelogin
url: https://github.com/elcajon/addon-simplelogin
version: 0.0.1
