arch:
- aarch64
- amd64
codenotary: agonist02_stiel@icloud.com
description: Fully featured Visual Studio Code (VSCode) experience integrated in the
  Home Assistant frontend.
docker_api: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
image: ghcr.io/elcajon/vscode/{arch}
ingress: true
ingress_port: 1337
ingress_stream: true
init: false
map:
- config:rw
- ssl:rw
- addons:rw
- media:rw
- share:rw
- backup:rw
name: Studio Code Server
panel_icon: mdi:microsoft-visual-studio-code
schema:
  init_path: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
services:
- mysql:want
- mqtt:want
slug: vscode
url: https://github.com/elcajon/addon-vscode
version: 6.0.13
