arch:
- aarch64
- amd64
description: Cloudflare Tunnel for proxy access
image: ghcr.io/elcajon/cloudflared/{arch}
init: false
map:
- share:rw
name: Cloudflare Tunnel
schema:
  tunnel: str?
slug: cloudflared
startup: services
url: https://github.com/elcajon/addon-cloudflared
version: 1.0.1
