arch:
- aarch64
- amd64
- armhf
- armv7
codenotary: codenotary@elcajon.dev
description: Zero config VPN for building secure networks
devices:
- /dev/net/tun
hassio_api: true
image: ghcr.io/elcajon-tech/tailscale/{arch}
ingress: true
ingress_stream: true
init: false
map:
- config:rw
- share:rw
- backup:rw
- media:rw
- addons:rw
- ssl:rw
name: Tailscale
panel_icon: mdi:vpn
privileged:
- NET_ADMIN
schema:
  enable_exit_node: bool?
  enable_ssh: bool?
  enable_subnets: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  tags:
  - match(^tag:[a-zA-Z0-9]-?[a-zA-Z0-9]+$)?
slug: tailscale
startup: services
url: https://github.com/elcajon-tech/addon-tailscale
version: 0.3.1
