arch:
- aarch64
- amd64
codenotary: codenotary@elcajon.dev
description: Zero config VPN for building secure networks
devices:
- /dev/net/tun
hassio_api: true
host_network: true
image: ghcr.io/elcajon-tech/tailscale/{arch}
ingress: true
ingress_port: 0
ingress_stream: true
init: false
map:
- config:ro
- share:ro
- backup:ro
- media:ro
- addons:ro
name: Tailscale
panel_icon: mdi:vpn
privileged:
- NET_ADMIN
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  tags:
  - match(^tag:[a-zA-Z0-9]-?[a-zA-Z0-9]+$)?
slug: tailscale
startup: services
url: https://github.com/elcajon-tech/addon-tailscale
version: 0.1.0
