name: Tailscale
version: 0.6.9
slug: tailscale
description: Zero config VPN for building secure networks
url: https://github.com/elcajon-tech/addon-tailscale
codenotary: codenotary@elcajon.dev
ingress: true
ingress_stream: true
startup: services
panel_icon: mdi:vpn
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
init: false
hassio_api: true
privileged:
- NET_ADMIN
devices:
- /dev/net/tun
host_network: true
map:
- config:rw
- share:rw
- backup:rw
- media:rw
- addons:rw
- ssl:rw
options:
  enable_funnel: false
  enable_exit_node: false
  enable_subnets: false
  enable_ssh: false
schema:
  enable_funnel: bool?
  enable_exit_node: bool?
  enable_subnets: bool?
  enable_ssh: bool?
  auth_key: str?
  tags:
  - match(^tag:[a-zA-Z0-9]-?[a-zA-Z0-9]+$)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.io/elcajon-tech/tailscale/{arch}
