---
name: NextDNS Router
version: 7695eea
slug: nextdns
description: NextDNS router for network wide ad-blocking
url: https://github.com/elcajon-tech/addon-nextdns
codenotary: codenotary@elcajon.dev
startup: services
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  53/udp: 53
ports_description:
  53/udp: DNS server port
options:
  subnet_config: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  default_config: match(^([a-zA-Z0-9_-]){6}$)?
  subnet_config:
    - match(^(([12]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])(.|\/)){4}([1-2]?[0-9]|3[0-2])=([a-zA-Z0-9_-]){6}$)?
  nextdns_log: bool?
