arch:
- aarch64
- amd64
codenotary: codenotary@elcajon.dev
description: NextDNS router for network wide ad-blocking
image: ghcr.io/elcajon-tech/nextdns/{arch}
init: false
name: NextDNS Router
options:
  subnet_config: []
ports:
  53/udp: 53
ports_description:
  53/udp: DNS server port
schema:
  default_config: match(^([a-zA-Z0-9_-]){6}$)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  nextdns_log: bool?
  subnet_config:
  - match(^(([12]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])(.|\/)){4}([1-2]?[0-9]|3[0-2])=([a-zA-Z0-9_-]){6}$)?
slug: nextdns
startup: services
url: https://github.com/elcajon-tech/addon-nextdns
version: 0.1.1
