apparmor: false
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
codenotary: agonist02_stiel@icloud.com
description: Generic add-on for development purposes
docker_api: true
full_access: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
image: ghcr.io/elcajon/generic/{arch}
init: false
map:
- config:rw
- ssl:rw
- addons:rw
- media:rw
- share:rw
- backup:rw
name: Generic
ports:
  8080/tcp: 8080
  8090/tcp: 8090
  8100/tcp: 8100
ports_description:
  8080/tcp: Sample interface 1
  8090/tcp: Sample interface 2
  8100/tcp: Sample interface 3
privileged:
- NET_ADMIN
- SYS_ADMIN
- SYS_RAWIO
- SYS_TIME
- SYS_NICE
slug: generic
url: https://github.com/elcajon/addon-generic
version: 0.0.12
